[2025-10-17T21:43:05.317+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-17T21:43:05.331+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_ingest_to_bronze.fetch_restcountries_to_parquet manual__2025-10-17T21:43:04.567592+00:00 [queued]>
[2025-10-17T21:43:05.334+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_ingest_to_bronze.fetch_restcountries_to_parquet manual__2025-10-17T21:43:04.567592+00:00 [queued]>
[2025-10-17T21:43:05.334+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-10-17T21:43:05.338+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_restcountries_to_parquet> on 2025-10-17 21:43:04.567592+00:00
[2025-10-17T21:43:05.342+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=264) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-10-17T21:43:05.343+0000] {standard_task_runner.py:63} INFO - Started process 267 to run task
[2025-10-17T21:43:05.343+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'api_ingest_to_bronze', 'fetch_restcountries_to_parquet', 'manual__2025-10-17T21:43:04.567592+00:00', '--job-id', '136', '--raw', '--subdir', 'DAGS_FOLDER/api_ingest_to_bronze_dag.py', '--cfg-path', '/tmp/tmpzbgp79lr']
[2025-10-17T21:43:05.344+0000] {standard_task_runner.py:91} INFO - Job 136: Subtask fetch_restcountries_to_parquet
[2025-10-17T21:43:05.350+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-10-17T21:43:05.363+0000] {task_command.py:426} INFO - Running <TaskInstance: api_ingest_to_bronze.fetch_restcountries_to_parquet manual__2025-10-17T21:43:04.567592+00:00 [running]> on host 728de341d734
[2025-10-17T21:43:05.393+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-eng' AIRFLOW_CTX_DAG_ID='api_ingest_to_bronze' AIRFLOW_CTX_TASK_ID='fetch_restcountries_to_parquet' AIRFLOW_CTX_EXECUTION_DATE='2025-10-17T21:43:04.567592+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-17T21:43:04.567592+00:00'
[2025-10-17T21:43:05.394+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-17T21:43:05.960+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-17T21:43:05.961+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/api_ingest_to_bronze_dag.py", line 43, in fetch_restcountries_to_parquet
    r.raise_for_status()
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://restcountries.com/v3.1/all
[2025-10-17T21:43:05.975+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=api_ingest_to_bronze, task_id=fetch_restcountries_to_parquet, run_id=manual__2025-10-17T21:43:04.567592+00:00, execution_date=20251017T214304, start_date=20251017T214305, end_date=20251017T214305
[2025-10-17T21:43:05.986+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 136 for task fetch_restcountries_to_parquet (400 Client Error: Bad Request for url: https://restcountries.com/v3.1/all; 267)
[2025-10-17T21:43:05.999+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-10-17T21:43:06.014+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-17T21:43:06.016+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
