[2025-10-16T01:37:41.616+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-16T01:37:41.631+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_to_bronze.parquet_to_snowflake manual__2025-10-16T01:36:34.042258+00:00 [queued]>
[2025-10-16T01:37:41.634+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_to_bronze.parquet_to_snowflake manual__2025-10-16T01:36:34.042258+00:00 [queued]>
[2025-10-16T01:37:41.634+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-10-16T01:37:41.643+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): parquet_to_snowflake> on 2025-10-16 01:36:34.042258+00:00
[2025-10-16T01:37:41.648+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=242) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-10-16T01:37:41.649+0000] {standard_task_runner.py:63} INFO - Started process 245 to run task
[2025-10-16T01:37:41.648+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ingest_to_bronze', 'parquet_to_snowflake', 'manual__2025-10-16T01:36:34.042258+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/api_ingest_to_bronze_dag.py', '--cfg-path', '/tmp/tmp0wm223bs']
[2025-10-16T01:37:41.650+0000] {standard_task_runner.py:91} INFO - Job 17: Subtask parquet_to_snowflake
[2025-10-16T01:37:41.657+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-10-16T01:37:41.672+0000] {task_command.py:426} INFO - Running <TaskInstance: ingest_to_bronze.parquet_to_snowflake manual__2025-10-16T01:36:34.042258+00:00 [running]> on host 728de341d734
[2025-10-16T01:37:41.703+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingest_to_bronze' AIRFLOW_CTX_TASK_ID='parquet_to_snowflake' AIRFLOW_CTX_EXECUTION_DATE='2025-10-16T01:36:34.042258+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-16T01:36:34.042258+00:00'
[2025-10-16T01:37:41.703+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-16T01:37:41.710+0000] {connection.py:399} INFO - Snowflake Connector for Python Version: 3.10.1, Python Version: 3.12.4, Platform: Linux-6.10.14-linuxkit-aarch64-with-glibc2.36
[2025-10-16T01:37:41.710+0000] {connection.py:1239} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-10-16T01:37:43.228+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2025-10-16T01:37:43.352+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2025-10-16T01:37:43.694+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2025-10-16T01:37:43.846+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2025-10-16T01:37:47.797+0000] {connection.py:762} INFO - closed
[2025-10-16T01:37:47.885+0000] {connection.py:768} INFO - No async queries seem to be running, deleting session
[2025-10-16T01:37:47.984+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-16T01:37:47.989+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/api_ingest_to_bronze_dag.py", line 56, in load_parquet_to_snowflake
    write_pandas(con, df, table_name=table, quote_identifiers=True)
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/pandas_tools.py", line 438, in write_pandas
    copy_results = cursor.execute(copy_into_sql, _is_internal=True).fetchall()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/cursor.py", line 1080, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 000904 (42000): 01bfbd01-0001-091c-0000-c8f10001e17a: SQL compilation error: error line 1 at position 94
invalid identifier '"iso_code"'
[2025-10-16T01:37:48.006+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=ingest_to_bronze, task_id=parquet_to_snowflake, run_id=manual__2025-10-16T01:36:34.042258+00:00, execution_date=20251016T013634, start_date=20251016T013741, end_date=20251016T013748
[2025-10-16T01:37:48.021+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 17 for task parquet_to_snowflake (000904 (42000): 01bfbd01-0001-091c-0000-c8f10001e17a: SQL compilation error: error line 1 at position 94
invalid identifier '"iso_code"'; 245)
[2025-10-16T01:37:48.063+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-10-16T01:37:48.075+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-16T01:37:48.076+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
