[2025-10-16T01:05:42.852+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-16T01:05:42.866+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_to_bronze.parquet_to_snowflake manual__2025-10-16T01:05:40.575433+00:00 [queued]>
[2025-10-16T01:05:42.869+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_to_bronze.parquet_to_snowflake manual__2025-10-16T01:05:40.575433+00:00 [queued]>
[2025-10-16T01:05:42.869+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-10-16T01:05:42.873+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): parquet_to_snowflake> on 2025-10-16 01:05:40.575433+00:00
[2025-10-16T01:05:42.877+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=241) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-10-16T01:05:42.878+0000] {standard_task_runner.py:63} INFO - Started process 244 to run task
[2025-10-16T01:05:42.877+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ingest_to_bronze', 'parquet_to_snowflake', 'manual__2025-10-16T01:05:40.575433+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/api_ingest_to_bronze_dag.py', '--cfg-path', '/tmp/tmpzng0c8xe']
[2025-10-16T01:05:42.878+0000] {standard_task_runner.py:91} INFO - Job 6: Subtask parquet_to_snowflake
[2025-10-16T01:05:42.884+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-10-16T01:05:42.896+0000] {task_command.py:426} INFO - Running <TaskInstance: ingest_to_bronze.parquet_to_snowflake manual__2025-10-16T01:05:40.575433+00:00 [running]> on host 580f10bff5a6
[2025-10-16T01:05:42.926+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingest_to_bronze' AIRFLOW_CTX_TASK_ID='parquet_to_snowflake' AIRFLOW_CTX_EXECUTION_DATE='2025-10-16T01:05:40.575433+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-16T01:05:40.575433+00:00'
[2025-10-16T01:05:42.926+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-16T01:05:42.933+0000] {connection.py:399} INFO - Snowflake Connector for Python Version: 3.10.1, Python Version: 3.12.4, Platform: Linux-6.10.14-linuxkit-aarch64-with-glibc2.36
[2025-10-16T01:05:42.936+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-16T01:05:42.936+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/api_ingest_to_bronze_dag.py", line 39, in load_parquet_to_snowflake
    con = connect(**{k:v for k,v in SF_CFG.items() if v})
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/__init__.py", line 55, in Connect
    return SnowflakeConnection(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/connection.py", line 440, in __init__
    kwargs = _get_default_connection_params()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/config_manager.py", line 473, in _get_default_connection_params
    raise Error(
snowflake.connector.errors.Error: Default connection with name 'default' cannot be found, known ones are []
[2025-10-16T01:05:42.940+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=ingest_to_bronze, task_id=parquet_to_snowflake, run_id=manual__2025-10-16T01:05:40.575433+00:00, execution_date=20251016T010540, start_date=20251016T010542, end_date=20251016T010542
[2025-10-16T01:05:42.944+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 6 for task parquet_to_snowflake (Default connection with name 'default' cannot be found, known ones are []; 244)
[2025-10-16T01:05:42.977+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-10-16T01:05:42.984+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-16T01:05:42.985+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
