[2025-10-16T01:30:49.911+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-16T01:30:49.923+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_to_bronze.local_to_parquet manual__2025-10-16T01:30:48.427059+00:00 [queued]>
[2025-10-16T01:30:49.926+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_to_bronze.local_to_parquet manual__2025-10-16T01:30:48.427059+00:00 [queued]>
[2025-10-16T01:30:49.927+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-10-16T01:30:49.931+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): local_to_parquet> on 2025-10-16 01:30:48.427059+00:00
[2025-10-16T01:30:49.936+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=187) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-10-16T01:30:49.936+0000] {standard_task_runner.py:63} INFO - Started process 190 to run task
[2025-10-16T01:30:49.936+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ingest_to_bronze', 'local_to_parquet', 'manual__2025-10-16T01:30:48.427059+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/api_ingest_to_bronze_dag.py', '--cfg-path', '/tmp/tmpgguak8h1']
[2025-10-16T01:30:49.937+0000] {standard_task_runner.py:91} INFO - Job 12: Subtask local_to_parquet
[2025-10-16T01:30:49.943+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-10-16T01:30:49.956+0000] {task_command.py:426} INFO - Running <TaskInstance: ingest_to_bronze.local_to_parquet manual__2025-10-16T01:30:48.427059+00:00 [running]> on host 384ae5693a5d
[2025-10-16T01:30:49.992+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingest_to_bronze' AIRFLOW_CTX_TASK_ID='local_to_parquet' AIRFLOW_CTX_EXECUTION_DATE='2025-10-16T01:30:48.427059+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-16T01:30:48.427059+00:00'
[2025-10-16T01:30:49.993+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-16T01:30:50.004+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-16T01:30:50.005+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/compat/_optional.py", line 132, in import_optional_dependency
    module = importlib.import_module(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'openpyxl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/api_ingest_to_bronze_dag.py", line 31, in ingest_local_to_parquet
    df = pd.read_excel(os.path.join(DATA_DIR, f))
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/excel/_base.py", line 504, in read_excel
    io = ExcelFile(
         ^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/excel/_base.py", line 1580, in __init__
    self._reader = self._engines[engine](
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/excel/_openpyxl.py", line 552, in __init__
    import_optional_dependency("openpyxl")
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/compat/_optional.py", line 135, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.
[2025-10-16T01:30:50.012+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=ingest_to_bronze, task_id=local_to_parquet, run_id=manual__2025-10-16T01:30:48.427059+00:00, execution_date=20251016T013048, start_date=20251016T013049, end_date=20251016T013050
[2025-10-16T01:30:50.017+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 12 for task local_to_parquet (Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.; 190)
[2025-10-16T01:30:50.033+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-10-16T01:30:50.051+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-16T01:30:50.053+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
