[2025-10-17T22:04:53.530+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-17T22:04:53.543+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: silver_to_gold.create_view_country_enriched manual__2025-10-17T22:04:46.017480+00:00 [queued]>
[2025-10-17T22:04:53.546+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: silver_to_gold.create_view_country_enriched manual__2025-10-17T22:04:46.017480+00:00 [queued]>
[2025-10-17T22:04:53.546+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-10-17T22:04:53.551+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): create_view_country_enriched> on 2025-10-17 22:04:46.017480+00:00
[2025-10-17T22:04:53.556+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=218) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-10-17T22:04:53.557+0000] {standard_task_runner.py:63} INFO - Started process 225 to run task
[2025-10-17T22:04:53.556+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'silver_to_gold', 'create_view_country_enriched', 'manual__2025-10-17T22:04:46.017480+00:00', '--job-id', '158', '--raw', '--subdir', 'DAGS_FOLDER/gold_build_dag.py', '--cfg-path', '/tmp/tmpde8hk0pl']
[2025-10-17T22:04:53.557+0000] {standard_task_runner.py:91} INFO - Job 158: Subtask create_view_country_enriched
[2025-10-17T22:04:53.568+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-10-17T22:04:53.585+0000] {task_command.py:426} INFO - Running <TaskInstance: silver_to_gold.create_view_country_enriched manual__2025-10-17T22:04:46.017480+00:00 [running]> on host 728de341d734
[2025-10-17T22:04:53.631+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-eng' AIRFLOW_CTX_DAG_ID='silver_to_gold' AIRFLOW_CTX_TASK_ID='create_view_country_enriched' AIRFLOW_CTX_EXECUTION_DATE='2025-10-17T22:04:46.017480+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-17T22:04:46.017480+00:00'
[2025-10-17T22:04:53.631+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-17T22:04:53.638+0000] {connection.py:399} INFO - Snowflake Connector for Python Version: 3.10.1, Python Version: 3.12.4, Platform: Linux-6.10.14-linuxkit-aarch64-with-glibc2.36
[2025-10-17T22:04:53.639+0000] {connection.py:1239} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-10-17T22:04:54.133+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2025-10-17T22:04:54.268+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2025-10-17T22:04:54.437+0000] {connection.py:762} INFO - closed
[2025-10-17T22:04:54.512+0000] {connection.py:768} INFO - No async queries seem to be running, deleting session
[2025-10-17T22:04:54.597+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-17T22:04:54.598+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/gold_build_dag.py", line 37, in run_sql
    cs.execute(stmt)
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/cursor.py", line 1080, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 000904 (42000): 01bfc76c-0001-0972-0000-c8f10003abca: SQL compilation error: error line 4 at position 20
invalid identifier 'C.CONTINENT'
[2025-10-17T22:04:54.613+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=silver_to_gold, task_id=create_view_country_enriched, run_id=manual__2025-10-17T22:04:46.017480+00:00, execution_date=20251017T220446, start_date=20251017T220453, end_date=20251017T220454
[2025-10-17T22:04:54.626+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 158 for task create_view_country_enriched (000904 (42000): 01bfc76c-0001-0972-0000-c8f10003abca: SQL compilation error: error line 4 at position 20
invalid identifier 'C.CONTINENT'; 225)
[2025-10-17T22:04:54.667+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-10-17T22:04:54.680+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-17T22:04:54.681+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
