[2025-10-16T02:21:34.895+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-16T02:21:34.907+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gold_build.run_sql manual__2025-10-16T02:21:33.935534+00:00 [queued]>
[2025-10-16T02:21:34.910+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gold_build.run_sql manual__2025-10-16T02:21:33.935534+00:00 [queued]>
[2025-10-16T02:21:34.911+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-10-16T02:21:34.915+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): run_sql> on 2025-10-16 02:21:33.935534+00:00
[2025-10-16T02:21:34.919+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=310) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-10-16T02:21:34.919+0000] {standard_task_runner.py:63} INFO - Started process 313 to run task
[2025-10-16T02:21:34.919+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'gold_build', 'run_sql', 'manual__2025-10-16T02:21:33.935534+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/gold_build_dag.py', '--cfg-path', '/tmp/tmpvv75bgee']
[2025-10-16T02:21:34.920+0000] {standard_task_runner.py:91} INFO - Job 45: Subtask run_sql
[2025-10-16T02:21:34.926+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-10-16T02:21:34.938+0000] {task_command.py:426} INFO - Running <TaskInstance: gold_build.run_sql manual__2025-10-16T02:21:33.935534+00:00 [running]> on host 728de341d734
[2025-10-16T02:21:34.966+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='gold_build' AIRFLOW_CTX_TASK_ID='run_sql' AIRFLOW_CTX_EXECUTION_DATE='2025-10-16T02:21:33.935534+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-16T02:21:33.935534+00:00'
[2025-10-16T02:21:34.966+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-16T02:21:34.972+0000] {connection.py:399} INFO - Snowflake Connector for Python Version: 3.10.1, Python Version: 3.12.4, Platform: Linux-6.10.14-linuxkit-aarch64-with-glibc2.36
[2025-10-16T02:21:34.972+0000] {connection.py:1239} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-10-16T02:21:35.908+0000] {connection.py:762} INFO - closed
[2025-10-16T02:21:35.995+0000] {connection.py:768} INFO - No async queries seem to be running, deleting session
[2025-10-16T02:21:36.100+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-16T02:21:36.103+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/gold_build_dag.py", line 37, in run_sql
    cs.execute(SQL.format(wh=os.getenv("SNOWFLAKE_WAREHOUSE"), db=os.getenv("SNOWFLAKE_DATABASE")))
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/cursor.py", line 1080, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 000008 (0A000): 01bfbd2d-0001-0927-0000-c8f10001d38e: Actual statement count 5 did not match the desired statement count 1.
[2025-10-16T02:21:36.124+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=gold_build, task_id=run_sql, run_id=manual__2025-10-16T02:21:33.935534+00:00, execution_date=20251016T022133, start_date=20251016T022134, end_date=20251016T022136
[2025-10-16T02:21:36.136+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 45 for task run_sql (000008 (0A000): 01bfbd2d-0001-0927-0000-c8f10001d38e: Actual statement count 5 did not match the desired statement count 1.; 313)
[2025-10-16T02:21:36.169+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-10-16T02:21:36.184+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-16T02:21:36.185+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
