[2025-10-16T01:45:13.768+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-16T01:45:13.781+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_to_bronze.parquet_to_snowflake manual__2025-10-16T01:44:13.172158+00:00 [queued]>
[2025-10-16T01:45:13.784+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_to_bronze.parquet_to_snowflake manual__2025-10-16T01:44:13.172158+00:00 [queued]>
[2025-10-16T01:45:13.784+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-10-16T01:45:13.788+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): parquet_to_snowflake> on 2025-10-16 01:44:13.172158+00:00
[2025-10-16T01:45:13.792+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=256) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-10-16T01:45:13.792+0000] {standard_task_runner.py:63} INFO - Started process 259 to run task
[2025-10-16T01:45:13.792+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ingest_to_bronze', 'parquet_to_snowflake', 'manual__2025-10-16T01:44:13.172158+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/api_ingest_to_bronze_dag.py', '--cfg-path', '/tmp/tmpsu45emwr']
[2025-10-16T01:45:13.793+0000] {standard_task_runner.py:91} INFO - Job 21: Subtask parquet_to_snowflake
[2025-10-16T01:45:13.799+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-10-16T01:45:13.811+0000] {task_command.py:426} INFO - Running <TaskInstance: ingest_to_bronze.parquet_to_snowflake manual__2025-10-16T01:44:13.172158+00:00 [running]> on host 728de341d734
[2025-10-16T01:45:13.845+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingest_to_bronze' AIRFLOW_CTX_TASK_ID='parquet_to_snowflake' AIRFLOW_CTX_EXECUTION_DATE='2025-10-16T01:44:13.172158+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-16T01:44:13.172158+00:00'
[2025-10-16T01:45:13.846+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-16T01:45:13.851+0000] {connection.py:399} INFO - Snowflake Connector for Python Version: 3.10.1, Python Version: 3.12.4, Platform: Linux-6.10.14-linuxkit-aarch64-with-glibc2.36
[2025-10-16T01:45:13.852+0000] {connection.py:1239} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-10-16T01:45:14.793+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2025-10-16T01:45:14.914+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2025-10-16T01:45:15.123+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2025-10-16T01:45:15.300+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2025-10-16T01:45:21.526+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2025-10-16T01:45:21.847+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2025-10-16T01:45:22.001+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2025-10-16T01:45:25.998+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2025-10-16T01:45:26.142+0000] {connection.py:762} INFO - closed
[2025-10-16T01:45:26.216+0000] {connection.py:768} INFO - No async queries seem to be running, deleting session
[2025-10-16T01:45:26.308+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-16T01:45:26.310+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/api_ingest_to_bronze_dag.py", line 60, in load_parquet_to_snowflake
    cs.execute(f'CREATE TABLE IF NOT EXISTS {table} ({cols})')
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/cursor.py", line 1080, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 001003 (42000): 01bfbd09-0001-08f7-0000-c8f10001f18e: SQL compilation error:
syntax error line 1 at position 52 unexpected ';'.
[2025-10-16T01:45:26.332+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=ingest_to_bronze, task_id=parquet_to_snowflake, run_id=manual__2025-10-16T01:44:13.172158+00:00, execution_date=20251016T014413, start_date=20251016T014513, end_date=20251016T014526
[2025-10-16T01:45:26.348+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 21 for task parquet_to_snowflake (001003 (42000): 01bfbd09-0001-08f7-0000-c8f10001f18e: SQL compilation error:
syntax error line 1 at position 52 unexpected ';'.; 259)
[2025-10-16T01:45:26.407+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-10-16T01:45:26.424+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-16T01:45:26.425+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
