[2025-10-17T00:12:39.809+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-17T00:12:39.822+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: silver_transform.run_sql manual__2025-10-17T00:12:38.856494+00:00 [queued]>
[2025-10-17T00:12:39.824+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: silver_transform.run_sql manual__2025-10-17T00:12:38.856494+00:00 [queued]>
[2025-10-17T00:12:39.825+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-10-17T00:12:39.829+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): run_sql> on 2025-10-17 00:12:38.856494+00:00
[2025-10-17T00:12:39.832+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=236) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-10-17T00:12:39.833+0000] {standard_task_runner.py:63} INFO - Started process 239 to run task
[2025-10-17T00:12:39.833+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'silver_transform', 'run_sql', 'manual__2025-10-17T00:12:38.856494+00:00', '--job-id', '90', '--raw', '--subdir', 'DAGS_FOLDER/silver_transform_dag.py', '--cfg-path', '/tmp/tmpea09iuy2']
[2025-10-17T00:12:39.834+0000] {standard_task_runner.py:91} INFO - Job 90: Subtask run_sql
[2025-10-17T00:12:39.839+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-10-17T00:12:39.852+0000] {task_command.py:426} INFO - Running <TaskInstance: silver_transform.run_sql manual__2025-10-17T00:12:38.856494+00:00 [running]> on host 728de341d734
[2025-10-17T00:12:39.883+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='silver_transform' AIRFLOW_CTX_TASK_ID='run_sql' AIRFLOW_CTX_EXECUTION_DATE='2025-10-17T00:12:38.856494+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-17T00:12:38.856494+00:00'
[2025-10-17T00:12:39.884+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-17T00:12:39.889+0000] {connection.py:399} INFO - Snowflake Connector for Python Version: 3.10.1, Python Version: 3.12.4, Platform: Linux-6.10.14-linuxkit-aarch64-with-glibc2.36
[2025-10-17T00:12:39.891+0000] {connection.py:1239} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-10-17T00:12:40.453+0000] {logging_mixin.py:188} INFO - 
[SQL] Executing statement:
USE WAREHOUSE COMPUTE_WH
[2025-10-17T00:12:40.566+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2025-10-17T00:12:40.567+0000] {logging_mixin.py:188} INFO - 
[SQL] Executing statement:
USE DATABASE COVID_DB
[2025-10-17T00:12:40.724+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2025-10-17T00:12:40.725+0000] {logging_mixin.py:188} INFO - 
[SQL] Executing statement:
CREATE SCHEMA IF NOT EXISTS SILVER
[2025-10-17T00:12:40.843+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2025-10-17T00:12:40.844+0000] {logging_mixin.py:188} INFO - 
[SQL] Executing statement:
CREATE OR REPLACE TABLE SILVER.CASES_CLEAN AS
SELECT *
FROM (
  SELECT
    UPPER("ISO_CODE") AS iso_code,
    CASE
      WHEN TRY_TO_DATE(TO_VARCHAR("DATE")) IS NOT NULL THEN TRY_TO_DATE(TO_VARCHAR("DATE"))
      WHEN TRY_TO_DATE(TO_VARCHAR("DATE"), 'YYYY-MM-DD') IS NOT NULL THEN TO_DATE(TO_VARCHAR("DATE"), 'YYYY-MM-DD')
      WHEN TRY_TO_DATE(TO_VARCHAR("DATE"), 'YYYY/MM/DD') IS NOT NULL THEN TO_...
[2025-10-17T00:12:41.005+0000] {connection.py:762} INFO - closed
[2025-10-17T00:12:41.081+0000] {connection.py:768} INFO - No async queries seem to be running, deleting session
[2025-10-17T00:12:41.176+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-17T00:12:41.178+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/silver_transform_dag.py", line 275, in run_sql
    cs.execute(stmt)
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/cursor.py", line 1080, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 001007 (22023): 01bfc24c-0001-092d-0000-c8f10002a646: SQL compilation error:
invalid type [TRY_TO_NUMBER(CASES_DATASET.DATE)] for parameter 'TO_NUMBER'
[2025-10-17T00:12:41.191+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=silver_transform, task_id=run_sql, run_id=manual__2025-10-17T00:12:38.856494+00:00, execution_date=20251017T001238, start_date=20251017T001239, end_date=20251017T001241
[2025-10-17T00:12:41.202+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 90 for task run_sql (001007 (22023): 01bfc24c-0001-092d-0000-c8f10002a646: SQL compilation error:
invalid type [TRY_TO_NUMBER(CASES_DATASET.DATE)] for parameter 'TO_NUMBER'; 239)
[2025-10-17T00:12:41.213+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-10-17T00:12:41.223+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-17T00:12:41.224+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
